// DATA COLLECTION
const collection = [
  {
    picture: "images/dondada.jpg",
    title: "philly flingo",
    author: ["Alpha Wann"],
    beatmaker: ["3010"],
    album: "don dada mixtape vol 1",
    releaseYear: "2020",
  },
  {
    picture: "images/pnl-cover-dans-la-legende.jpg",
    title: "Humain",
    author: ["PNL"],
    beatmaker: ["Iksma Riddim"],
    album: "Dans la légende",
    releaseYear: "2016",
  },
  {
    picture: "images/raw-z.jpeg",
    title: "I Don't: Need u / Know",
    author: ["Laylow"],
    beatmaker: ["thescam", "Laylow"],
    album: ".RAW-Z",
    releaseYear: "2018",
  },
  {
    picture: "images/trinity.jpeg",
    title: "VAMONOS",
    author: ["Laylow", "Alpha Wann"],
    beatmaker: ["Dioscures"],
    album: "TRINITY",
    releaseYear: "2020",
  },
  {
    picture: "images/669p2.jpeg",
    title: "669, Pt.2",
    author: ["669"],
    beatmaker: ["669"],
    album: "single",
    releaseYear: "2021",
  },
  {
    picture: "images/Kekra_2018_Land_cover.jpg",
    title: "Wing Chun",
    author: ["Kekra"],
    beatmaker: ["Kirill Magai"],
    album: "Land",
    releaseYear: "2018",
  },
  {
    picture: "images/gouapswitch3.jpg",
    title: "Switch 3",
    author: ["Gouap"],
    beatmaker: ["Gouap"],
    album: 'Trilogie "Switch"',
    releaseYear: "2021",
  },
  {
    picture: "images/XEU.jpg",
    title: "Chépakichui",
    author: ["VALD"],
    beatmaker: ["Seezy"],
    album: "XEU",
    releaseYear: "2018",
  },
  {
    picture: "images/vrealite.jpg",
    title: "OSMS",
    author: ["Kekra"],
    beatmaker: ["Boumidjal WWD"],
    album: "Vréalité",
    releaseYear: "2019",
  },
  {
    picture: "images/S_O_le_Flem.jpg",
    title: "Fléau",
    author: ["Django"],
    beatmaker: ["Flem KGB"],
    album: "S/O le Flem",
    releaseYear: "2020",
  },
  {
    picture: "images/UNE_MAIN_LAVE_L_AUTRE.jpg",
    title: "CONTREX",
    author: ["Alpha Wann"],
    beatmaker: ["Jay Jay", "LamaOnTheBeat"],
    album: "UNE MAIN LAVE L'AUTRE",
    releaseYear: "2018",
  },
  {
    picture: "images/Projet_Blue_Beam.jpg",
    title: "Baton Rouge",
    author: ["Freeze Corleone"],
    beatmaker: ["Issa Diakhate"],
    album: "Projet Blue Beam",
    releaseYear: "2018",
  },
  {
    picture: "images/lala.jpeg",
    title: "Tous les jours",
    author: ["Lala &ce", "Jorrdee", "Retro X"],
    beatmaker: ["Tommy Kruise", "Lala &ce"],
    album: "Le son d'après",
    releaseYear: "2019",
  },
  {
    picture: "images/Ce_monde_est_cruel.jpg",
    title: "Rappel",
    author: ["VALD"],
    beatmaker: ["Zeg P"],
    album: "Ce monde est cruel",
    releaseYear: "2019",
  },
  {
    picture: "images/courier.jpeg",
    title: "Courrier",
    author: ["7 Jaws"],
    beatmaker: ["Seezy"],
    album: "Freestyle RAGE",
    releaseYear: "2020",
  },
  {
    picture: "images/retro24.jpeg",
    title: "VANESSA LAMARCK",
    author: ["Retro X"],
    beatmaker: ["Retro X"],
    album: "24",
    releaseYear: "2019",
  },
  {
    picture: "images/Ce_monde_est_cruel.jpg",
    title: "J'pourrai",
    author: ["VALD"],
    beatmaker: ["Seezy"],
    album: "Ce monde est cruel",
    releaseYear: "2019",
  },
  {
    picture: "images/argata.jpeg",
    title: "Kid Cudi",
    author: ["VALD"],
    beatmaker: ["Dj Weedim"],
    album: "Agartha",
    releaseYear: "2017",
  },
  {
    picture: "images/purification.jpeg",
    title: "Purification",
    author: ["AlKpote", "Freeze Corleone"],
    beatmaker: ["Dj Weedim"],
    album: "Les marches de l'empereur Saison 3",
    releaseYear: "2019",
  },
  {
    picture: "images/S_O_le_Flem.jpg",
    title: "Pyramide",
    author: ["Django", "Osirus Jack"],
    beatmaker: ["Flem KGB", "Amine Farsi"],
    album: "S/O le Flem",
    releaseYear: "2020",
  },
  {
    picture: "images/Echelon_Vol_1_Compilation.jpg",
    title: "Gotaga",
    author: ["VALD"],
    beatmaker: ["Seezy"],
    album: "Echelon, Vol. 1",
    releaseYear: "2020",
  },
  {
    picture: "images/VU.png",
    title: "J'aime personne, je t'aime",
    author: ["LL", "Jorrdee"],
    beatmaker: ["Jorrdee"],
    album: "VU",
    releaseYear: "2019",
  },
  {
    picture: "images/Rien_100_rien.jpg",
    title: "Salvatrucha",
    author: ["Jul"],
    beatmaker: ["Jul"],
    album: "Rien 100 Rien",
    releaseYear: "2019",
  },
  {
    picture: "images/Freebase_Vol_04_Mixtape_Street.jpg",
    title: "Bravoure",
    author: ["Kekra"],
    beatmaker: ["Boumidjal WWD", "Kekra"],
    album: "Freebase, Vol.04",
    releaseYear: "2020",
  },
  {
    picture: "images/Horizon_vertical.jpg",
    title: "Royal cheese",
    author: ["Heuss L'enfoiré", "VALD"],
    beatmaker: ["Seezy", "Zeg P"],
    album: "Horizon vertical",
    releaseYear: "2020",
  },
  {
    picture: "images/Horizon_vertical.jpg",
    title: "Diviser pour mieux régner",
    author: ["Heuss L'enfoiré", "VALD"],
    beatmaker: ["Zeg P", "Seezy"],
    album: "Horizon vertical",
    releaseYear: "2020",
  },
  {
    picture: "images/Horizon_vertical.jpg",
    title: "Adios",
    author: ["Heuss L'enfoiré", "VALD"],
    beatmaker: ["Suikon Blaze AD", "Seezy", "Zeg P"],
    album: "Horizon vertical",
    releaseYear: "2020",
  },
  {
    picture: "images/jorrdee0.4.jpeg",
    title: "Bigo",
    author: ["Jorrdee"],
    beatmaker: ["Izen High Zen"],
    album: "0.4",
    releaseYear: "2019",
  },
  {
    picture: "images/Nibiru.jpg",
    title: "Sacrifice de Masse, Pt2",
    author: ["Osirus Jack", "Freeze Corleone"],
    beatmaker: ["Osirus Jack"],
    album: "Nibiru",
    releaseYear: '"2021"',
  },
  {
    picture: "images/Nibiru.jpg",
    title: "C.E.R.N.",
    author: ["Osirus Jack"],
    beatmaker: ["Osirus Jack"],
    album: "Nibiru",
    releaseYear: '"2021"',
  },
  {
    picture: "images/LMF.jpg",
    title: "Rap catéchisme",
    author: ["Freeze Corleone", "Alpha Wann"],
    beatmaker: ["Flem KGB", "Jay Jay", "Ocho"],
    album: "LMF",
    releaseYear: "2020",
  },
  {
    picture: "images/dondada.jpg",
    title: "ny à fond",
    author: ["Alpha Wann", "Freeze Corleone"],
    beatmaker: ["Jay Jay", "Flem KGB", "LamaOnTheBeat", "Congo Bill", "M.O.I"],
    album: "don dada mixtape vol 1",
    releaseYear: "2020",
  },
];
